name: ci

on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/ci.yml
      - go.mod
      - go.sum

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7
      DOCKERHUB_USERNAME: isac322
      REPOSITORY: grafana-rollout-operator
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Get target repo version
        id: version
        run: |
          echo "version=$(go list -f '{{ .Version }}' -m 'github.com/grafana/rollout-operator')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          path: rollout-operator
          repository: grafana/rollout-operator
          ref: ${{ steps.version.outputs.version }}

      - name: Overwrite Dockerfile
        run: |
          cp -f Dockerfile rollout-operator/Dockerfile

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Enable buildkit cache
        uses: isac322/builtkit-state@v1
        with:
          buildx-name: ${{ steps.buildx.outputs.name }}
          cache-key: ${{ runner.os }}-buildkit-${{ steps.version.outputs.version }}
          cache-restore-key: |
            ${{ runner.os }}-buildkit-

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: rollout-operator
          push: false
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
