name: publish

on:
  release:
    types: [released]

  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7
      DOCKERHUB_USERNAME: isac322
      REPOSITORY: grafana-rollout-operator
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Get target repo version
        id: version
        run: |
          echo "version=$(go list -f '{{ .Version }}' -m 'github.com/grafana/rollout-operator')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          path: rollout-operator
          repository: grafana/rollout-operator
          ref: ${{ steps.version.outputs.version }}

      - name: Overwrite Dockerfile
        run: |
          cp -f Dockerfile rollout-operator/Dockerfile

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          flavor: latest=false
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
          labels: |
            maintainer=${{ env.DOCKERHUB_USERNAME }}
            org.opencontainers.image.title=rollout-operator
            org.opencontainers.image.source="https://github.com/grafana/rollout-operator"

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Enable buildkit cache
        uses: isac322/builtkit-state@v1
        with:
          buildx-name: ${{ steps.buildx.outputs.name }}
          cache-key: ${{ runner.os }}-buildkit-${{ steps.version.outputs.version }}
          cache-restore-key: |
            ${{ runner.os }}-buildkit-

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: rollout-operator
          push: true
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
